"""autogenerated by genpy from ee_cart_imped_msgs/StiffPoint.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import genpy
import std_msgs.msg

class StiffPoint(genpy.Message):
  _md5sum = "2b6b597656e805a0ca2e1de07dc31a66"
  _type = "ee_cart_imped_msgs/StiffPoint"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
#The pose to achieve in the stiffness directions
geometry_msgs/Pose pose
#Wrench or stiffness for each dimension
geometry_msgs/Wrench wrench_or_stiffness
#The following are True if a force/torque should
#be exerted and False if a stiffness should be used.
bool isForceX
bool isForceY
bool isForceZ
bool isTorqueX
bool isTorqueY
bool isTorqueZ
#The time from the start of the trajectory that this
#point should be achieved.
duration time_from_start
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Wrench
# This represents force in free space, seperated into 
# it's linear and angular parts.  
Vector3  force
Vector3  torque

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 

float64 x
float64 y
float64 z
"""
  __slots__ = ['header','pose','wrench_or_stiffness','isForceX','isForceY','isForceZ','isTorqueX','isTorqueY','isTorqueZ','time_from_start']
  _slot_types = ['std_msgs/Header','geometry_msgs/Pose','geometry_msgs/Wrench','bool','bool','bool','bool','bool','bool','duration']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,pose,wrench_or_stiffness,isForceX,isForceY,isForceZ,isTorqueX,isTorqueY,isTorqueZ,time_from_start

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(StiffPoint, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.wrench_or_stiffness is None:
        self.wrench_or_stiffness = geometry_msgs.msg.Wrench()
      if self.isForceX is None:
        self.isForceX = False
      if self.isForceY is None:
        self.isForceY = False
      if self.isForceZ is None:
        self.isForceZ = False
      if self.isTorqueX is None:
        self.isTorqueX = False
      if self.isTorqueY is None:
        self.isTorqueY = False
      if self.isTorqueZ is None:
        self.isTorqueZ = False
      if self.time_from_start is None:
        self.time_from_start = genpy.Duration()
    else:
      self.header = std_msgs.msg.Header()
      self.pose = geometry_msgs.msg.Pose()
      self.wrench_or_stiffness = geometry_msgs.msg.Wrench()
      self.isForceX = False
      self.isForceY = False
      self.isForceZ = False
      self.isTorqueX = False
      self.isTorqueY = False
      self.isTorqueZ = False
      self.time_from_start = genpy.Duration()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_13d6B2i.pack(_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.wrench_or_stiffness.force.x, _x.wrench_or_stiffness.force.y, _x.wrench_or_stiffness.force.z, _x.wrench_or_stiffness.torque.x, _x.wrench_or_stiffness.torque.y, _x.wrench_or_stiffness.torque.z, _x.isForceX, _x.isForceY, _x.isForceZ, _x.isTorqueX, _x.isTorqueY, _x.isTorqueZ, _x.time_from_start.secs, _x.time_from_start.nsecs))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.wrench_or_stiffness is None:
        self.wrench_or_stiffness = geometry_msgs.msg.Wrench()
      if self.time_from_start is None:
        self.time_from_start = genpy.Duration()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 118
      (_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.wrench_or_stiffness.force.x, _x.wrench_or_stiffness.force.y, _x.wrench_or_stiffness.force.z, _x.wrench_or_stiffness.torque.x, _x.wrench_or_stiffness.torque.y, _x.wrench_or_stiffness.torque.z, _x.isForceX, _x.isForceY, _x.isForceZ, _x.isTorqueX, _x.isTorqueY, _x.isTorqueZ, _x.time_from_start.secs, _x.time_from_start.nsecs,) = _struct_13d6B2i.unpack(str[start:end])
      self.isForceX = bool(self.isForceX)
      self.isForceY = bool(self.isForceY)
      self.isForceZ = bool(self.isForceZ)
      self.isTorqueX = bool(self.isTorqueX)
      self.isTorqueY = bool(self.isTorqueY)
      self.isTorqueZ = bool(self.isTorqueZ)
      self.time_from_start.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_13d6B2i.pack(_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.wrench_or_stiffness.force.x, _x.wrench_or_stiffness.force.y, _x.wrench_or_stiffness.force.z, _x.wrench_or_stiffness.torque.x, _x.wrench_or_stiffness.torque.y, _x.wrench_or_stiffness.torque.z, _x.isForceX, _x.isForceY, _x.isForceZ, _x.isTorqueX, _x.isTorqueY, _x.isTorqueZ, _x.time_from_start.secs, _x.time_from_start.nsecs))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose is None:
        self.pose = geometry_msgs.msg.Pose()
      if self.wrench_or_stiffness is None:
        self.wrench_or_stiffness = geometry_msgs.msg.Wrench()
      if self.time_from_start is None:
        self.time_from_start = genpy.Duration()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 118
      (_x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.orientation.x, _x.pose.orientation.y, _x.pose.orientation.z, _x.pose.orientation.w, _x.wrench_or_stiffness.force.x, _x.wrench_or_stiffness.force.y, _x.wrench_or_stiffness.force.z, _x.wrench_or_stiffness.torque.x, _x.wrench_or_stiffness.torque.y, _x.wrench_or_stiffness.torque.z, _x.isForceX, _x.isForceY, _x.isForceZ, _x.isTorqueX, _x.isTorqueY, _x.isTorqueZ, _x.time_from_start.secs, _x.time_from_start.nsecs,) = _struct_13d6B2i.unpack(str[start:end])
      self.isForceX = bool(self.isForceX)
      self.isForceY = bool(self.isForceY)
      self.isForceZ = bool(self.isForceZ)
      self.isTorqueX = bool(self.isTorqueX)
      self.isTorqueY = bool(self.isTorqueY)
      self.isTorqueZ = bool(self.isTorqueZ)
      self.time_from_start.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_13d6B2i = struct.Struct("<13d6B2i")
