/* Auto-generated by genmsg_cpp for file /home/robo328d/fuerte_workspace/ee_cart_imped/ee_cart_imped_msgs/msg/EECartImpedFeedback.msg */
#ifndef EE_CART_IMPED_MSGS_MESSAGE_EECARTIMPEDFEEDBACK_H
#define EE_CART_IMPED_MSGS_MESSAGE_EECARTIMPEDFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "ee_cart_imped_msgs/StiffPoint.h"
#include "ee_cart_imped_msgs/StiffPoint.h"
#include "ee_cart_imped_msgs/StiffPoint.h"
#include "ee_cart_imped_msgs/StiffPoint.h"

namespace ee_cart_imped_msgs
{
template <class ContainerAllocator>
struct EECartImpedFeedback_ {
  typedef EECartImpedFeedback_<ContainerAllocator> Type;

  EECartImpedFeedback_()
  : header()
  , goal()
  , initial_point()
  , desired()
  , actual_pose()
  , effort_sq_error(0.0)
  , requested_joint_efforts()
  , actual_joint_efforts()
  , running_time()
  {
  }

  EECartImpedFeedback_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , goal(_alloc)
  , initial_point(_alloc)
  , desired(_alloc)
  , actual_pose(_alloc)
  , effort_sq_error(0.0)
  , requested_joint_efforts(_alloc)
  , actual_joint_efforts(_alloc)
  , running_time()
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::ee_cart_imped_msgs::StiffPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ee_cart_imped_msgs::StiffPoint_<ContainerAllocator> >::other >  _goal_type;
  std::vector< ::ee_cart_imped_msgs::StiffPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ee_cart_imped_msgs::StiffPoint_<ContainerAllocator> >::other >  goal;

  typedef  ::ee_cart_imped_msgs::StiffPoint_<ContainerAllocator>  _initial_point_type;
   ::ee_cart_imped_msgs::StiffPoint_<ContainerAllocator>  initial_point;

  typedef  ::ee_cart_imped_msgs::StiffPoint_<ContainerAllocator>  _desired_type;
   ::ee_cart_imped_msgs::StiffPoint_<ContainerAllocator>  desired;

  typedef  ::ee_cart_imped_msgs::StiffPoint_<ContainerAllocator>  _actual_pose_type;
   ::ee_cart_imped_msgs::StiffPoint_<ContainerAllocator>  actual_pose;

  typedef double _effort_sq_error_type;
  double effort_sq_error;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _requested_joint_efforts_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  requested_joint_efforts;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _actual_joint_efforts_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  actual_joint_efforts;

  typedef ros::Duration _running_time_type;
  ros::Duration running_time;


  typedef boost::shared_ptr< ::ee_cart_imped_msgs::EECartImpedFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ee_cart_imped_msgs::EECartImpedFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct EECartImpedFeedback
typedef  ::ee_cart_imped_msgs::EECartImpedFeedback_<std::allocator<void> > EECartImpedFeedback;

typedef boost::shared_ptr< ::ee_cart_imped_msgs::EECartImpedFeedback> EECartImpedFeedbackPtr;
typedef boost::shared_ptr< ::ee_cart_imped_msgs::EECartImpedFeedback const> EECartImpedFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ee_cart_imped_msgs::EECartImpedFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ee_cart_imped_msgs::EECartImpedFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ee_cart_imped_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ee_cart_imped_msgs::EECartImpedFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ee_cart_imped_msgs::EECartImpedFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ee_cart_imped_msgs::EECartImpedFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4106b02683301dac2003809bdf610591";
  }

  static const char* value(const  ::ee_cart_imped_msgs::EECartImpedFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4106b02683301dacULL;
  static const uint64_t static_value2 = 0x2003809bdf610591ULL;
};

template<class ContainerAllocator>
struct DataType< ::ee_cart_imped_msgs::EECartImpedFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ee_cart_imped_msgs/EECartImpedFeedback";
  }

  static const char* value(const  ::ee_cart_imped_msgs::EECartImpedFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ee_cart_imped_msgs::EECartImpedFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
#current pose and squared error in force \n\
#and the running time of this goal so far\n\
Header header\n\
ee_cart_imped_msgs/StiffPoint[] goal\n\
ee_cart_imped_msgs/StiffPoint initial_point\n\
ee_cart_imped_msgs/StiffPoint desired\n\
ee_cart_imped_msgs/StiffPoint actual_pose\n\
float64 effort_sq_error\n\
float64[] requested_joint_efforts\n\
float64[] actual_joint_efforts\n\
duration running_time\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: ee_cart_imped_msgs/StiffPoint\n\
Header header\n\
#The pose to achieve in the stiffness directions\n\
geometry_msgs/Pose pose\n\
#Wrench or stiffness for each dimension\n\
geometry_msgs/Wrench wrench_or_stiffness\n\
#The following are True if a force/torque should\n\
#be exerted and False if a stiffness should be used.\n\
bool isForceX\n\
bool isForceY\n\
bool isForceZ\n\
bool isTorqueX\n\
bool isTorqueY\n\
bool isTorqueZ\n\
#The time from the start of the trajectory that this\n\
#point should be achieved.\n\
duration time_from_start\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Wrench\n\
# This represents force in free space, seperated into \n\
# it's linear and angular parts.  \n\
Vector3  force\n\
Vector3  torque\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::ee_cart_imped_msgs::EECartImpedFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::ee_cart_imped_msgs::EECartImpedFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::ee_cart_imped_msgs::EECartImpedFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ee_cart_imped_msgs::EECartImpedFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.goal);
    stream.next(m.initial_point);
    stream.next(m.desired);
    stream.next(m.actual_pose);
    stream.next(m.effort_sq_error);
    stream.next(m.requested_joint_efforts);
    stream.next(m.actual_joint_efforts);
    stream.next(m.running_time);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct EECartImpedFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ee_cart_imped_msgs::EECartImpedFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ee_cart_imped_msgs::EECartImpedFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal[]" << std::endl;
    for (size_t i = 0; i < v.goal.size(); ++i)
    {
      s << indent << "  goal[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ee_cart_imped_msgs::StiffPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.goal[i]);
    }
    s << indent << "initial_point: ";
s << std::endl;
    Printer< ::ee_cart_imped_msgs::StiffPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.initial_point);
    s << indent << "desired: ";
s << std::endl;
    Printer< ::ee_cart_imped_msgs::StiffPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.desired);
    s << indent << "actual_pose: ";
s << std::endl;
    Printer< ::ee_cart_imped_msgs::StiffPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.actual_pose);
    s << indent << "effort_sq_error: ";
    Printer<double>::stream(s, indent + "  ", v.effort_sq_error);
    s << indent << "requested_joint_efforts[]" << std::endl;
    for (size_t i = 0; i < v.requested_joint_efforts.size(); ++i)
    {
      s << indent << "  requested_joint_efforts[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.requested_joint_efforts[i]);
    }
    s << indent << "actual_joint_efforts[]" << std::endl;
    for (size_t i = 0; i < v.actual_joint_efforts.size(); ++i)
    {
      s << indent << "  actual_joint_efforts[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.actual_joint_efforts[i]);
    }
    s << indent << "running_time: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.running_time);
  }
};


} // namespace message_operations
} // namespace ros

#endif // EE_CART_IMPED_MSGS_MESSAGE_EECARTIMPEDFEEDBACK_H

